FROM python:alpine
RUN apk --update add --no-cache build-base libffi-dev openssl-dev ffmpeg imagemagick6

RUN mkdir -p /usr/local/app/foggycam2/capture

COPY src/ /usr/local/app/foggycam2
WORKDIR /usr/local/app/foggycam2

RUN pip3 install --upgrade pip \
 && pip3 install -r requirements.txt

VOLUME ["/usr/local/app/foggycam2/capture"]
VOLUME ["/usr/local/app/config.json"]

CMD ["/usr/local/app/foggycam2/foggycam2.py"]
